# Generated by Django 6.0.2 on 2026-03-25 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_parkingspace_parking_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='qr_image',
            field=models.ImageField(blank=True, null=True, upload_to='qr/'),
        ),
    ]
