# Generated by Django 6.0.2 on 2026-03-25 05:03

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_reservation_qr_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='qr_image',
            field=models.ImageField(blank=True, null=True, upload_to=api.models._qr_image_upload_path),
        ),
    ]
